language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: cOwoEceB5WMjKA+V4VExzVpgYyqlgkt/Sfyf8aQecxCIHeAT4qEhJEiFWnDw3b9AQZuO8rcmsGyzbyat0x3EjBZhAlHl5Hh1hofKaU+awx2Jp/OGzt60GBztprqCqcSv5DcuX1/klyAO9grRJUdx+gjJkVXFuxAPrEqiHhX/azAYy6WXFJwi4JpAxK8wsfPOpI2CcNdpw3QjZ4rTBlQyaOSkUq3pf4n2obxUCjLf37nds3IVIQpeXUEc77wRALRTge3//2JeA5/SydOg7tnJzoss1lvGb8GZnNLxnh5L5pA1u7sWnfILaS+fItJmDw7MiCuzylWnAXBykKUMB+vvC3PfTED6Y3Z/OzJAkdLiGaW11l3Try/nPnwVksYn/bxArf3qjn71Gxb0onNyHUI0Ukde+iJy0+Vlx/EamwNu1L2MHyNL34M7mQBE4NiKaQtkL/ibT8buC/624c8GkFruBpxqgA1AfoOx+CWV5pE1xrR6qusZjcbKGjmPSeu/vys5f/B1l2ddfRhny3lvdUzbmWoFWSopNeQ4uZILxS4L0LjdOK89o36QWT4+VDTeE1+fXxUPxIOzYzofidVhe+MMq7iJ4f8qFhhUf6vyrig3OyDXUfCqCyCz7cqPsVlsonEspduCyjhvhg8UCAZarcYqz22LhJO1JvxhcBC3gMYIc/0=
  app: react-resume-mui
  on:
    repo: mccloud-jeff/react-resume-mui
